
##################################################################################
######### A p p l i c a t i o n #########
#########################################

application: wave-skimmy
version: 10
runtime: python
api_version: 1

##################################################################################
############ H A N D L E R S ############
#########################################

handlers:

############ W e b ############

- url: /
  script: main.py

############ W a v e ############

- url: /_wave/.*
  script: main.py

############ S t a t i c ############

- url: /public/(.*)
  static_files: public/\1
  upload: public/(.*)
